# Discord Bot Configuration
bot:
  # Discord Bot Token (use environment variable BOT_TOKEN)
  token: ${BOT_TOKEN}
  # Bot command prefix (for hybrid commands)
  prefix: "!"
  # Bot activity status
  activity:
    type: "playing"  # playing, watching, listening
    name: "Advanced Admin Commands"
  # Bot presence status
  status: "online"  # online, idle, dnd, invisible

# Server Configuration
server:
  # Port for webhooks and web interfaces
  port: 3001
  # Host binding
  host: "0.0.0.0"

# Color Scheme
colors:
  primary: "#ba4628"      # Primary color (red-orange)
  secondary: "#56f87b"    # Secondary color (green)
  error: "#ff4757"        # Error color
  warning: "#ffa502"      # Warning color
  success: "#2ed573"      # Success color
  info: "#5352ed"         # Info color

# Permissions System
permissions:
  # Default admin role names that can use admin commands
  admin_roles:
    - "Admin"
    - "Administrator"
    - "Owner"
    - "Moderator"
  # Require specific permissions for certain commands
  required_permissions:
    ban: "ban_members"
    kick: "kick_members"
    purge: "manage_messages"
    mute: "manage_roles"
    eval: "administrator"
    shutdown: "administrator"

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Log channel ID for bot logs (leave empty to disable)
  log_channel_id: ${LOG_CHANNEL_ID:}
  # File logging settings
  file_logging:
    enabled: true
    max_size: "10 MB"
    backup_count: 5
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} | {message}"

# Command Configuration
commands:
  # Global command cooldown (seconds)
  global_cooldown: 3
  # Per-user command cooldown (seconds)  
  user_cooldown: 5
  # Enable command usage statistics
  enable_stats: true
  # Default ephemeral response for admin commands
  default_ephemeral: false

# Database Configuration (optional)
database:
  # Database type: sqlite, postgresql
  type: "sqlite"
  # SQLite settings
  sqlite:
    path: "data/bot.db"
  # PostgreSQL settings (if using postgresql)
  postgresql:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    user: ${DB_USER:}
    password: ${DB_PASSWORD:}
    database: ${DB_NAME:discord_bot}

# Cog Configuration
cogs:
  # Auto-load these cogs on startup
  autoload:
    - "cogs.admin"
    - "cogs.moderation" 
    - "cogs.utility"
    - "cogs.advanced_admin"
    - "cogs.system_admin"
  # Reload cogs on file changes (development only)
  auto_reload: false

# Feature Flags
features:
  # Enable advanced logging with colored console output
  colored_console: true
  # Enable command usage statistics
  command_statistics: true
  # Enable error reporting to log channel
  error_reporting: true
  # Enable automatic backup system
  auto_backup: false
  # Enable AI integration support
  ai_integration: false

# External API Configuration
apis:
  # OpenAI API Key (for AI features)
  openai_key: ${OPENAI_API_KEY:}
  # Other API keys can be added here
  webhook_url: ${WEBHOOK_URL:}